// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SampleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "C:\\firefox\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sample() {
    driver.get("https://www.facebook.com/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    assertThat(driver.findElement(By.name("login")).getText(), is("Log In"));
    assertThat(driver.findElement(By.linkText("Forgotten password?")).getText(), is("Forgotten password?"));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("sankarnarayanan");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("12345");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).click();
    {
      WebElement element = driver.findElement(By.id("email"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("email")).click();
    {
      WebElement element = driver.findElement(By.id("email"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      String value = driver.findElement(By.id("email")).getAttribute("value");
      assertThat(value, is("sankarnarayanan"));
    }
    driver.navigate().refresh();
    driver.navigate().forward();
    driver.navigate().back();
  }
}
